source "https://github.com/CocoaPods/Specs.git"
platform:ios, 8.0
use_frameworks!

target "Example" do

	pod "SnapKit", "~> 4.0.0"
	pod "MZFormSheetPresentationController"
    pod "SwiftyJSON", "~> 4.0.0"
end
